-- 코드를 작성해주세요
SELECT L.DEPT_ID
     , L.DEPT_NAME_EN
     , ROUND(AVG(R.SAL), 0) AS AVG_SAL
  FROM HR_DEPARTMENT L
 INNER JOIN HR_EMPLOYEES R ON L.DEPT_ID = R.DEPT_ID
 GROUP BY L.DEPT_ID
 ORDER BY AVG(R.SAL) DESC