-- 코드를 작성해주세요
SELECT COUNT(FISH_TYPE) AS FISH_COUNT
     , CAST(SUBSTR(TIME,6,2) AS DECIMAL) AS MONTH
  FROM FISH_INFO
 GROUP BY CAST(SUBSTR(TIME,6,2) AS DECIMAL)
 ORDER BY CAST(SUBSTR(TIME,6,2) AS DECIMAL)