-- 코드를 작성해주세요
SELECT COUNT(FISH_TYPE) AS FISH_COUNT
     , MAX(LENGTH) AS MAX_LENGTH
     , FISH_TYPE
  FROM FISH_INFO
 GROUP BY FISH_TYPE
 HAVING SUM(IFNULL(LENGTH, 10)) / COUNT(FISH_TYPE) >= 33
 ORDER BY FISH_TYPE