-- 코드를 작성해주세요
SELECT YEAR(YM)               AS `YEAR`
     , ROUND(AVG(PM_VAL1), 2) AS `PM10`
     , ROUND(AVG(PM_VAL2), 2) AS `PM2.5`
  FROM AIR_POLLUTION
 WHERE LOCATION2 = '수원'
 GROUP BY YEAR(YM)
 ORDER BY YEAR(YM)

-- 오답 처리된 코드
SELECT SUBSTR(YM,1,4)         AS `YEAR`
     , ROUND(AVG(PM_VAL1), 2) AS `PM10`
     , ROUND(AVG(PM_VAL2), 2) AS `PM2.5`
  FROM AIR_POLLUTION
 WHERE LOCATION2 = '수원'
 GROUP BY SUBSTR(YM,1,4)
 ORDER BY SUBSTR(YM,1,4)

 -- 오답 처리된 코드2
SELECT DATE_FORMAT(YM,'%Y')   AS `YEAR`
     , ROUND(AVG(PM_VAL1), 2) AS `PM10`
     , ROUND(AVG(PM_VAL2), 2) AS `PM2.5`
  FROM AIR_POLLUTION
 WHERE LOCATION2 = '수원'
 GROUP BY DATE_FORMAT(YM,'%Y')
 ORDER BY DATE_FORMAT(YM,'%Y')