-- 코드를 작성해주세요

SELECT COUNT(L.FISH_TYPE) AS FISH_COUNT
     , R.FISH_NAME
  FROM FISH_INFO L
 INNER JOIN FISH_NAME_INFO R ON L.FISH_TYPE = R.FISH_TYPE
 GROUP BY L.FISH_TYPE
        , R.FISH_NAME
 ORDER BY COUNT(L.FISH_TYPE) DESC