-- 코드를 작성해주세요
SELECT A.ID
     , B.FISH_NAME
     , A.LENGTH
  FROM FISH_INFO A
INNER JOIN
(SELECT L.FISH_TYPE
     , R.FISH_NAME
     , MAX(L.LENGTH) AS LENGTH
  FROM FISH_INFO L
 INNER JOIN FISH_NAME_INFO R ON L.FISH_TYPE = R.FISH_TYPE
 GROUP BY L.FISH_TYPE
        , R.FISH_NAME) B ON A.FISH_TYPE = B.FISH_TYPE AND A.LENGTH = B.LENGTH
ORDER BY A.ID
