SELECT T.ITEM_ID
     , T.ITEM_NAME
     , T.RARITY
  FROM
        (SELECT L.ITEM_ID
             , L.ITEM_NAME
             , L.RARITY
             , (SELECT RARITY FROM ITEM_INFO WHERE ITEM_ID = R.PARENT_ITEM_ID) AS BEFORE_RARITY
          FROM ITEM_INFO L
         INNER JOIN ITEM_TREE R ON L.ITEM_ID = R.ITEM_ID
         WHERE R.PARENT_ITEM_ID IS NOT NULL) T
 WHERE T.BEFORE_RARITY = 'RARE'
 ORDER BY ITEM_ID DESC